name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run 1.py
        run: python 1.py

      - name: Run 2.py
        run: python 2.py

      - name: Merge into id.json
        run: python merge.py

      - name: Commit and push id.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔁 Update id.json"
          file_pattern: "id.json"
